# PixelPilot configuration
#
# This file contains runtime settings and feature switches.

[system]
# Listen address for RTP video stream. (Default: 0.0.0.0)
listen_address=0.0.0.0

# UDP port for RTP video stream. (Default: 5600)
listen_port=5602

# Read data from socket.
socket=

# Log verbosity level: debug|info|warn|error. (Default: info)
log_level=debug

# Override default screen mode. Format: <width>x<height>@<fps>, ex: 1920x1080@120
screen_mode=

# Target DRM refresh rate for mode selection (30..120), ex: 60.
# Makes DRM choose the highest available resolution at the requested FPS.
# For optimal smoothness, use a value equal to or divisible by the video FPS.
target_frame_rate=60

# Enable VSYNC commits. (Default: true)
vsync=true

# Port of wfb-server for CLI statistics. 0 = disabled. (Default: 8003)
wfb_port=8003

# Path to a PNG image to display on the screensaver.
screensaver_image=

[osd]
# Enable OSD. (Default: false)
enabled=true

# Path to OSD configuration file.
config=/etc/pixelpilot/config_osd.json

# Delay between OSD refreshes. (Default: 1000 ms)
refresh_ms=100

[osd.widgets]
# Enable or disable OSD widgets by ID from config_osd.json.
video_fps_resolution=true
video_link_bitrate=true
signal_snr=true
signal_rssi=true
dvr_storage=true
wfb_status=true
drone_status=true
dvr_status=true
msposd=true

[dvr]
# Enable DVR functionality. (Default: true)
start=true

# Save the video feed (no OSD) to the provided filename template.
# DVR is toggled by SIGUSR1 signal.
# Supported placeholders:
#   %N - sequence number
#   %Y - year
#   %m - month
#   %d - day
#   %H - hour
#   %M - minute
#   %S - second
# Example: /media/DVR/%N_%Y-%m-%d_%H-%M-%S.ts
template=/mnt/udisk/%N_%Y-%m-%d_%H-%M-%S.mp4

# Burn OSD into DVR recording (WYSIWYG via DRM writeback). (Default: false)
osd=false

# Target bitrate for DVR re-encoding. (Default: 8000000)
bitrate=8000000

# Start a new DVR file every N minutes. 0 = disabled. (Default: 0)
segment_time_min=0

# Stop/refuse DVR recording below this free space. (Default: 200 MB)
min_free_mb=200

# Only record if the DVR directory is on a mounted external device. (Default: false)
require_mount=true
