#ifndef RUNNING_AVERAGE_HPP
#define RUNNING_AVERAGE_HPP

#include <cstdlib>
#include <deque>
#include <vector>

// Struct to hold extended statistics
struct Stats {
    long min;
    long max;
    double average;
    long sum;
    int count;

    Stats(long min_value, long max_value, double avg, long total_sum, int total_count)
        : min(min_value), max(max_value), average(avg), sum(total_sum), count(total_count) {}
};

/**
 * Calculates the running average/rate-per-second/min/max over a sliding time window.
 * @param window_size_ms the size of the sliding window in milliseconds
 * @param bucket_size_ms the size of the bucket; structure uses amount of memory
 *		  of O(window_size_ms / bucket_size_ms), however large bucket size decreases the precision.
 * NOTE: the code was mostly generated by ChatGPT
 */
class RunningAverage {
  public:
    RunningAverage(int window_size_ms, int bucket_size_ms);

    long add(long value);

    double average_over_last_ms(uint last_ms) const;

    double rate_per_second_over_last_ms(uint last_ms) const;

    void get_stats_over_last_ms(uint last_ms, long &min, long &max, double &average) const;

    // New method to return Stats struct with sum and count
    Stats get_stats_over_last_ms_result(uint last_ms) const;

    std::vector<long> get_bucket_sums() const;
    std::vector<Stats> get_bucket_stats() const;

  private:
    struct Bucket {
        long long timestamp;
        long sum;
        int count;
        long min_value;
        long max_value;

        Bucket(long long ts, long value) : timestamp(ts), sum(value), count(1), min_value(value), max_value(value) {}
    };

    void calculate_stats_in_window(uint last_ms, long &sum_out, int &count_out, long &min_out, long &max_out) const;

    int window_size;
    int bucket_size;
    std::deque<Bucket> buckets;
    long sum;
    int count;
};

#endif
